### ISSUE TITLE
Is there a way to estimate the share of refugees in population by region?

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/lebanon-economic-monitor#23]
Is there a way to estimate the share of refugees in population by region?

**Comment by jfulponi** [comment]
I only found data at country level. Maybe some inference from population data and the aggregated data? Like zones that have been growing more than others or in similar levels to the general movement.

**Comment by g4brielvs** [comment]
The UNHCR operational data is only available at national level, , but some data is disaggregated. 

- https://data2.unhcr.org/en/situations/syria/location/71

**Comment by g4brielvs** [comment]
The mobility data or other available data sources are inadequate. This analysis will not move forward.
