### ISSUE TITLE
Issue on page /notebooks/ntl-analysis/README.html

### ISSUE THREAD

**Issue by Jagbakpe** [datapartnership/lebanon-economic-monitor#50]
I followed the link provided to get the dataset, I opened the data archive hyperlink and saw a series of data sets with no clear description. Is it possible that the actual dataset name from the archive can be provided so I can find the dataset?

**Comment by g4brielvs** [comment]
> I followed the link provided to get the dataset, I opened the data archive hyperlink and saw a series of data sets with no clear description. Is it possible that the actual dataset name from the archive can be provided so I can find the dataset?

@ramarty Would you be able to assist?

**Comment by Jagbakpe** [comment]
The meeting we had last week addressed this issue, thank you very much!
