### ISSUE TITLE
Issue on page /notebooks/ais-analysis/README.html

### ISSUE THREAD

**Issue by Jagbakpe** [datapartnership/lebanon-economic-monitor#55]
Unable to sign in to sharepoint.

error message below:

If that doesn't help, contact your support team and include these technical details:
Correlation ID: 45e316a1-4016-5000-16e5-d26067ee4baf
Date and Time: 3/20/2024 6:22:57 AM
URL: https://worldbankgroup.sharepoint.com/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared Documents/Forms/AllItems.aspx?cid=fccdf23e-94d5-48bf-b75d-0af291138bde&csf=1&e=Yvwh8r&FolderCTID=0x012000CFAB9FF0F938A64EBB297E7E16BDFCFD&id=%2Fteams%2FDevelopmentDataPartnershipCommunity-WBGroup%2FShared+Documents%2FProjects%2FData+Lab%2FLebanon+Economic+Analytics%2FData%2Ftrade&viewid=80cdadb3-8bb3-47ae-8b18-c1dd89c373c5&web=1
User: Josephine.AgbakpeKa@bison.howard.edu
Issue Type: User not in directory.

**Comment by g4brielvs** [comment]
Not in scope of [Howard University's Review](https://worldbank.github.io/data-good-training/docs/review-timeline.html#timeline-of-the-review).
