### ISSUE TITLE
Issue on page /notebooks/ais-analysis/README.html

### ISSUE THREAD

**Issue by Jagbakpe** [datapartnership/lebanon-economic-monitor#56]
"The difference in arrival vs. departure **draught** is a key calculation to estimate trade. However, the difference between outgoing and incoming draft is only identified in a subset of port calls. For the remaining routes, we apply the back-propagation technique, searching for the arrival draft at the next port visited."

Is " "draft" supposed to be "draught" here?

**Comment by g4brielvs** [comment]
> "The difference in arrival vs. departure **draught** is a key calculation to estimate trade. However, the difference between outgoing and incoming draft is only identified in a subset of port calls. For the remaining routes, we apply the back-propagation technique, searching for the arrival draft at the next port visited."
> 
> Is " "draft" supposed to be "draught" here?

@Jagbakpe Thanks! @andresfchamorro Would you be able to assist?
