### ISSUE TITLE
Lebanon | Update ACLED Analysis

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/lebanon-economic-monitor#93]
Update the notebook and produce pretty maps for Lebanon till October 2024 showing fatalities from the recent war.

**Comment by jlucab** [comment]
Will have it all done and all data + visuals saved on OneDrive

**Comment by SahitiSarva** [comment]
- Make the charts start on October 7th 2023 till date.

**Comment by SahitiSarva** [comment]
Team asked for another update by the end of the week

**Comment by jlucab** [comment]
Will you send me the updated data today?

**Comment by SahitiSarva** [comment]
The maps created by @jlucab were shared with the team.
